name: ascan2_tf1
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.16.0
  - pip
  - pip:
      - tensorflow==1.12.0
      - biopython==1.69
      - h5py==2.8.0
      - Keras==2.2.4
      - scikit-learn>=0.20.1